Lesson 5
========================================================
```{r}
library(ggplot2)
library(dplyr)
library(gridExtra)
fb_users = read.csv('pseudo_facebook.tsv', sep='\t')
```


```{r Third Qualitative Variable}
ggplot(aes(x = gender, y = age),
       data = subset(fb_users, !is.na(gender))) + geom_boxplot() +
  stat_summary(fun.y=mean, geom='point', shape=4)

ggplot(aes(x = age, y = friend_count),
       data = subset(fb_users, !is.na(gender))) +
  geom_line(aes(color=gender), stat='summary', fun.y=median)

#GroupBy Age and Gender
age_gender_group = group_by(na.omit(fb_users), age, gender)
fb_users.age_gender = summarise(age_gender_group,
                                mean_friend_count = mean(friend_count),
                                median_friend_count = median(friend_count),
                                n = n())
fb_users.age_gender
```

***

### Plotting Conditional Summaries
Notes:

```{r Plotting Conditional Summaries}
p1 = ggplot(aes(x=age, y=mean_friend_count, color=gender), data=fb_users.age_gender) +
  geom_line() +
  ggtitle('Mean Friend Count by Gender')
p2 = ggplot(aes(x=age, y=median_friend_count, color=gender), data=fb_users.age_gender) +
  geom_line()
  ggtitle('Median Friend Count by Gender')

grid.arrange(p1, p2)
g = arrangeGrob(p1, p2)
ggsave('visualizations/MeanMedianFriendsCounts_byGender.png', g)
```

### Reshaping Data

```{r}
#library(reshape2)
#fb_users.age_gender.wide = dcast(fb_users.age_gender,
#                                 age ~ gender,
#                                 value.var = "median_friend_count")
#head(fb_users.age_gender.wide)

library(tidyr)
fb_users.age_gender.wide_tidyr = fb_users.age_gender[c('age', 'gender', 'median_friend_count')] %>%
  spread(gender, median_friend_count) %>%
  mutate(ratio=female/male)
head(fb_users.age_gender.wide_tidyr)
```


***

### Ratio Plot
Notes:

```{r Ratio Plot}
ggplot(aes(x=age, y=ratio), data=fb_users.age_gender.wide_tidyr) +
  geom_line() + 
  geom_line(y=1, alpha=.75, linetype=3) +
  ylab('Ratio of Females to Males') + xlab('Age') + 
  ggtitle('Ratio of Females to Males by Age') +
ggsave('visualizations/RatioFemalesMales_byAge.png')
```

***

### Third Quantitative Variable

```{r Third Quantitative Variable}
fb_users$year_joined = floor(2014 - fb_users$tenure / 365)
head(fb_users)
```

***

### Cut a Variable

```{r Cut a Variable}
summary(fb_users$year_joined)
table(fb_users$year_joined)
fb_users$year_joined.bucket = cut(fb_users$year_joined, c(2004,2009,2011,2012,2014))
table(fb_users$year_joined.bucket)
```

***

### Plotting it All Together
Notes:

```{r Plotting it All Together}
ggplot(aes(x=age, y=friend_count, color=year_joined.bucket), data=na.omit(fb_users)) + 
  geom_line(stat='summary', fun.y=median) +
  ggtitle('Median Friend Count by Age and Year Joined')
```

***

### Plot the Grand Mean
Notes:

```{r Plot the Grand Mean}
ggplot(aes(x=age, y=friend_count), data=na.omit(fb_users)) + 
  geom_line(aes(color=year_joined.bucket), stat='summary', fun.y=mean) +
  geom_line(stat='summary', fun.y=mean, linetype=2, alpha=.75, size=.5) +
  ggtitle('Mean Friend Count by Age and Year Joined')
ggsave('visualizations/Friends_byAgeYearJoined.png')
```

***

### Friending Rate
What is the median friend rate?
What is the maximum friend rate?

```{r Friending Rate}
with(subset(na.omit(fb_users), tenure>0), summary(friend_count / tenure))
```

***

### Friendships Initiated

```{r Friendships Initiated}
ggplot(aes(x=tenure, y=friendships_initiated / tenure), data=subset(na.omit(fb_users), fb_users$tenure >0)) +
  geom_line(aes(color=year_joined.bucket), stat='summary', fun.y='mean') +
  geom_smooth(aes(color=year_joined.bucket), alpha=.5) +
  ylab('Friendships Initiated per Day') + xlab('Tenure') +
  ggtitle('Friendships Initiated per Day by Tenure by Year Joined')
ggsave('visualizations/FriendshipsInitiatedPerDay_byTenurebyYearJoined.png')
```

***

### Bias-Variance Tradeoff Revisited
Notes:

```{r Bias-Variance Tradeoff Revisited}
library(ggplot2)
ggplot(aes(x = tenure, y = friendships_initiated / tenure),
       data = subset(fb_users, tenure >= 1)) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary',
            fun.y = mean)

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(fb_users, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 30 * round(tenure / 30), y = friendships_initiated / tenure),
       data = subset(fb_users, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

ggplot(aes(x = 90 * round(tenure / 90), y = friendships_initiated / tenure),
       data = subset(fb_users, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

```

***
```{r Scatterplot Matrices}
library(GGally)
set.seed(1836)
fb_users_subset = fb_users[,c('age', 'dob_year', 'dob_month', 'gender', 'friend_count', 'mobile_likes', 'friendships_initiated', 'tenure')]
g = ggpairs(fb_users_subset[sample.int(nrow(fb_users_subset),1000),])
print(g)
ggsave('visualizations/PlotMatrix.png', g)
```
